apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-lh-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
      - name: sonarr
        image: linuxserver/sonarr
        imagePullPolicy: Always
        ports:
        - containerPort: 8989
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          - name: sonarr-lh
            mountPath: /config
          - name: media
            mountPath: /media
      volumes:
      - name: sonarr-lh
        persistentVolumeClaim:
          claimName: sonarr-lh-pvc
      - name: media
        nfs:
          server: 192.168.1.5
          path: /volume1/media-meta
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr-svc
spec:
  selector:
    app: sonarr
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989
