---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
     project_dir : "../"
  tasks:
  - name: terraform init
    command: "terraform init {{ project_dir }} "
    register: init_result
  - name: terraform apply
    terraform:
      project_path: "{{ project_dir }}"
      state: present
    register: apply_result

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: node
  become: yes
  roles:
    - role: k3s/node

# Replace the K3s included Traefik manifest
#- hosts: master
#  become: yes
#  tasks:
#  - name: Copy Traefik manifest
#    copy:
#      src: '../k3s/traefik.yaml'
#      dest: '/var/lib/rancher/k3s/server/manifests/traefik.yaml'
#  - name: Restart K3s service
#    systemd:
#      name: k3s
#      daemon_reload: yes
#      state: restarted
#      enabled: yes

# Bootstrap cluster with
# Longhorn: distributed storage
# MetalLB: BGP advertisement with router
- hosts: localhost
  tasks:
  - name: Create MetalLB Namespace
    k8s:
      state: present
      src: '../k3s/metallb-namespace.yaml'

  - name: Install MetalLB
    k8s:
      state: present
      src: '../k3s/metallb-install.yaml'
  - name: Create MetalLB secret
    command: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="ORsap03Le8v5YWRHYV8vjF65bG1Smbl1p3z2fNkzGEKdKRm6Xuai/Htjzwtzrsf+Y0IXGy6TOLnaOBn3gHK2/57Za6X+LHu9xzW7+mvbkrdqkZHvmxYRjLSk8Qt9cAosf/6PLvk/gc6XWkqUNz3bUwzNzInRkhXLkchcOg5kCI4="
    ignore_errors: true

  - name: Configure MetalLB
    k8s:
      state: present
      src: '../k3s/metallb-config.yml'

  - name: Install Longhorn
    k8s:
      state: present
      src: '../k3s/longhorn-install.yaml'

