#cloud-config
runcmd:
  - curl -fsSL https://get.docker.io | sh
  - systemctl enable docker
  - systemctl start docker
  - docker run -d --restart=unless-stopped --name=rancher -p 80:80 -p 443:443 rancher/rancher:latest
